name: CI

on:
  push:
    branches: [ master ]
jobs:
  Build and Publish:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Set npm registy and Publish the package
        run: |
          echo '//registry.npmjs.org/:_authToken=${{ secrets.NPM_PROFILE_AUTHTOKEN }}' >> ~/.npmrc
          npm publish
