name: CI

on: [ pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Check if version has been updated
      - id: check
        uses: EndBug/version-check@v1
        with:
          file-url: https://unpkg.com/vgs-delivery@latest/package.json
          static-checking: localIsNew

      - name: Log when unchanged
        if: steps.check.outputs.changed != 'true'
        run: exit 1
